import ThemeRegistry from "@/theme/ThemeRegistry";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <Providers>{children}</Providers>
        </body>
      </ThemeRegistry>
    </html>
  );
}
